### ISSUE TITLE
The app redirects the user to the landing page.

### ISSUE THREAD

**Issue by AdithyaBhat17** [bapspatil/Rake#1]
Redirect it to the dashboard page instead https://rake.now.sh/#/dashboard/labelled-images @bapspatil

**Comment by bapspatil** [comment]
Done.

**Comment by bapspatil** [comment]
On picker screen, it'll redirect to Dashboard.
On image labeling screen, it'll redirect to Dashboard/Labelled-Images.

**Comment by AdithyaBhat17** [comment]
ok 👍
